backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "source/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "/data/home.yml"
        preview_path: "/index"
        editor:
             preview: false
        fields:
          - {label: Header, name: header, widget: string}
          - {label: Header Description, name: header_description, widget: string}
          - {label: Challenge Title, name: challenge_title, widget: string}
          - {label: Challenge Body, name: challenge_body, widget: text}
          - {label: Opportunity Title, name: opportunity_title, widget: string}
          - {label: Opportunity Body, name: opportunity_body, widget: text}
          - {label: Approach Title, name: approach_title, widget: string}
          - {label: Approach Element One Title, name: approach_element_one_title, widget: string}
          - {label: Approach Element One Body, name: approach_element_one_body, widget: text}
          - {label: Approach Element Two Title, name: approach_element_two_title, widget: string}
          - {label: Approach Element Two Body, name: approach_element_two_body, widget: text}
          - {label: Approach Element Three Title, name: approach_element_three_title, widget: string}
          - {label: Approach Element Three Body, name: approach_element_three_body, widget: text}
      - label: "Contact"
        name: "contact"
        file: "/data/contact.yml"
        preview_path: "/contact"
        editor:
             preview: false
        fields:
          - {label: Contact Form Prompt, name: prompt, widget: text}
  - label: "Analytics"
    name: "analytics"
    files:
      fields:
        - {label: test, name: test, widget: string}

